### ISSUE TITLE
Consecutive publish not received

### ISSUE THREAD

**Issue by favetelinguis** [wise-home/hub#27]
In a test im sending concecutive publish like this:
```
    Hub.publish(market_id, {:marketTime, Timex.shift(Timex.now(), hours: 3)})
    |> IO.inspect()
    Hub.publish(market_id, {:batl, 19467345, [[0, 2.82, 22.93], [1, 2.72, 4.91]]})
    |> IO.inspect()
```
Giving the output 1,0.
However if I change to
```
    Hub.publish(market_id, {:marketTime, Timex.shift(Timex.now(), hours: 3)})
    |> IO.inspect()
    Process.sleep(3000)
    Hub.publish(market_id, {:batl, 19467345, [[0, 2.82, 22.93], [1, 2.72, 4.91]]})
    |> IO.inspect()
```
Im getting the output 1, 1

Why do I need a sleep? My thought was that subscribers get the message delivered to the mail box but now it looks like if a consumer is bussy consuming a message it will never get delivered?

**Comment by favetelinguis** [comment]
Found the error in how I subscribe, I make two separate subscriptions and the second one had not yet subscribed before the test sends to it.

**Comment by lasseebert** [comment]
I'm happy that it worked out.

This is the first issue not written by me, so I'm also happy someone else is using the package. If you have any problems, just open another issue ☺️
